#!/usr/bin/env node

/**
 * pr-split.mjs — Deterministic operations for PR splitting.
 *
 * Used by the pr-split Claude Code skill. All git operations, worktree
 * management, manifest CRUD, verification, and PR creation are handled here.
 * The AI agent only handles: diff analysis, file grouping, descriptions,
 * and user interaction.
 *
 * Directory structure (tree'd per branch):
 *   {project}-pr-worktrees/
 *     {safe-branch}/
 *       manifest.json
 *       01-{slug}/        ← git worktree
 *       02-{slug}/        ← git worktree
 *
 * Zero external dependencies — uses only Node.js built-ins.
 */

import { execSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
  rmSync,
  rmdirSync,
} from "node:fs";
import { basename, dirname, join } from "node:path";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function git(cmd, opts = {}) {
  const { cwd, allowFail = false } = opts;
  try {
    return execSync(`git ${cmd}`, {
      cwd,
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
  } catch (err) {
    if (allowFail) return "";
    throw err;
  }
}

function run(cmd, opts = {}) {
  const { cwd, allowFail = false, inheritStdio = false } = opts;
  try {
    if (inheritStdio) {
      execSync(cmd, { cwd, stdio: "inherit" });
      return "";
    }
    return execSync(cmd, {
      cwd,
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
  } catch (err) {
    if (allowFail) return err.stderr || err.stdout || "";
    throw err;
  }
}

function getRepoRoot() {
  return git("rev-parse --show-toplevel");
}

function getRepoName() {
  return basename(getRepoRoot());
}

function getCurrentBranch() {
  return git("branch --show-current");
}

function safeBranchName(branch) {
  return branch.replace(/\//g, "--");
}

function getWorktreeParent() {
  const root = getRepoRoot();
  return join(dirname(root), `${getRepoName()}-pr-worktrees`);
}

function getBranchDir(safeBranch) {
  return join(getWorktreeParent(), safeBranch);
}

function getManifestPath(safeBranch) {
  return join(getBranchDir(safeBranch), "manifest.json");
}

function getPartDir(safeBranch, part) {
  const padded = String(part.order).padStart(2, "0");
  return join(getBranchDir(safeBranch), `${padded}-${part.slug}`);
}

function readManifest(safeBranch) {
  const p = getManifestPath(safeBranch);
  if (existsSync(p)) {
    return JSON.parse(readFileSync(p, "utf-8"));
  }
  return null;
}

function writeManifest(safeBranch, manifest) {
  const p = getManifestPath(safeBranch);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, JSON.stringify(manifest, null, 2) + "\n");
}

function requireManifest(safeBranch) {
  const m = readManifest(safeBranch);
  if (!m) {
    console.error(
      `ERROR: No manifest found at ${getManifestPath(safeBranch)}. Run plan-save first.`,
    );
    process.exit(1);
  }
  return m;
}

function getPart(manifest, order) {
  const part = manifest.parts.find((p) => p.order === order);
  if (!part) {
    console.error(`ERROR: Part ${order} not found.`);
    process.exit(1);
  }
  return part;
}

function now() {
  return new Date().toISOString();
}

function buildPrBody(manifest, part) {
  const activeParts = manifest.parts.filter((p) => p.status !== "merged");

  const reviewLines = activeParts
    .map((p) => {
      if (p.order === part.order) {
        return `- #${p.prNumber} 👈`;
      } else if (p.prNumber) {
        return `- #${p.prNumber}`;
      } else {
        return `- _(pending)_`;
      }
    })
    .join("\n");

  return `## Summary
${part.description}

## Part of
Split from branch \`${manifest.sourceBranch}\` — Part ${part.order}/${part.total}

## Review order
This is PR ${part.order} of ${part.total}. Review in order for best understanding.

${reviewLines}

---
Generated by pr-split skill`;
}

// ─── Commands ────────────────────────────────────────────────────────────────

function cmdPreflight() {
  let errors = 0;
  console.log("Checking dependencies...");

  try {
    const v = run("git --version");
    console.log(`  OK: ${v}`);
  } catch {
    console.log("  FAIL: git not found");
    errors++;
  }

  try {
    run("gh --version");
    console.log("  OK: gh CLI found");
  } catch {
    console.log("  WARN: gh CLI not found — PR creation will be skipped");
  }

  if (errors > 0) {
    console.log(`\nFAIL: ${errors} missing required dependency(ies).`);
    process.exit(1);
  }
  console.log("\nAll required dependencies present.");
}

function cmdContext(baseBranch = "main") {
  const repoRoot = getRepoRoot();
  const repoName = getRepoName();
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const branchDir = getBranchDir(safeBranch);
  const manifestPath = getManifestPath(safeBranch);

  let dirty = false;
  try {
    git("diff --quiet HEAD");
    git("diff --cached --quiet");
  } catch {
    dirty = true;
  }

  let hasGh = false;
  try {
    run("which gh");
    hasGh = true;
  } catch {}

  const hasManifest = existsSync(manifestPath);

  const context = {
    repoRoot,
    repoName,
    currentBranch,
    baseBranch,
    worktreeParent: getWorktreeParent(),
    branchDir,
    manifestPath,
    safeBranch,
    dirty,
    hasGh,
    hasManifest,
  };

  console.log(JSON.stringify(context, null, 2));
}

function cmdDiff(baseBranch = "main") {
  console.log("=== DIFF STAT ===");
  console.log(
    git(`diff ${baseBranch}...HEAD --stat`, { allowFail: true }) ||
      "(no changes)",
  );

  console.log("\n=== NAME STATUS ===");
  console.log(
    git(`diff ${baseBranch}...HEAD --name-status`, { allowFail: true }) ||
      "(no changes)",
  );

  console.log("\n=== COMMIT LOG ===");
  console.log(
    git(`log ${baseBranch}...HEAD --oneline`, { allowFail: true }) ||
      "(no commits)",
  );

  console.log("\n=== FULL DIFF ===");
  console.log(
    git(`diff ${baseBranch}...HEAD`, { allowFail: true }) || "(no diff)",
  );
}

function cmdManifestRead() {
  const safeBranch = safeBranchName(getCurrentBranch());
  const manifest = readManifest(safeBranch);
  console.log(JSON.stringify(manifest || {}, null, 2));
}

function cmdPlanSave() {
  const input = readFileSync("/dev/stdin", "utf-8");
  let plan;
  try {
    plan = JSON.parse(input);
  } catch {
    console.error("ERROR: Invalid JSON on stdin");
    process.exit(1);
  }

  // Validate no duplicate files across parts
  const allFiles = plan.parts.flatMap((p) => p.files);
  const dups = allFiles.filter((f, i) => allFiles.indexOf(f) !== i);
  if (dups.length > 0) {
    console.error(
      `ERROR: Duplicate files across parts: ${[...new Set(dups)].join(", ")}`,
    );
    process.exit(1);
  }

  const repoName = getRepoName();
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);

  const existing = readManifest(safeBranch);
  const total = plan.parts.length;

  const manifest = {
    version: 2,
    repoName,
    sourceBranch: currentBranch,
    baseBranch: plan.baseBranch,
    featureTag: plan.featureTag,
    createdAt: existing?.createdAt || now(),
    updatedAt: now(),
    parts: plan.parts.map((p) => ({
      order: p.order,
      total,
      slug: p.slug,
      branch: p.branch,
      title: p.title,
      description: p.description,
      files: p.files,
      fileActions: p.fileActions,
      status: "pending",
      prNumber: null,
      prUrl: null,
    })),
  };

  writeManifest(safeBranch, manifest);
  console.log(`Manifest saved to ${getManifestPath(safeBranch)}`);
}

function cmdExecute(partNumber) {
  if (!partNumber) {
    console.error("Usage: pr-split.mjs execute <part-number>");
    process.exit(1);
  }
  const order = parseInt(partNumber, 10);
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = requireManifest(safeBranch);
  const part = getPart(manifest, order);

  const worktreePath = getPartDir(safeBranch, part);

  // Clean up existing worktree if present
  if (existsSync(worktreePath)) {
    console.log(`Removing existing worktree at ${worktreePath}...`);
    git(`worktree remove "${worktreePath}" --force`, { allowFail: true });
    git(`branch -D "${part.branch}"`, { allowFail: true });
  }

  // Create worktree from base branch
  const branchDir = getBranchDir(safeBranch);
  console.log(`Creating worktree: ${worktreePath}`);
  mkdirSync(branchDir, { recursive: true });
  git(
    `worktree add "${worktreePath}" -b "${part.branch}" "${manifest.baseBranch}"`,
  );

  // Apply files
  console.log("Applying files...");
  for (const file of part.files) {
    const action = part.fileActions?.[file] || "M";

    if (action === "D") {
      console.log(`  rm ${file}`);
      git(`rm "${file}"`, { cwd: worktreePath, allowFail: true });
    } else {
      console.log(`  checkout ${file} (${action})`);
      const fileDir = join(worktreePath, dirname(file));
      mkdirSync(fileDir, { recursive: true });
      git(`checkout "${currentBranch}" -- "${file}"`, { cwd: worktreePath });
    }
  }

  // Commit
  console.log("Committing...");
  git("add -A", { cwd: worktreePath });

  const commitMsg = `${part.title}\n\n${part.description}\n\nSplit from: ${currentBranch}\n\nCo-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>`;
  const msgFile = join(worktreePath, ".pr-split-commit-msg");
  writeFileSync(msgFile, commitMsg);
  git(`commit --no-verify -F "${msgFile}"`, { cwd: worktreePath });
  rmSync(msgFile, { force: true });

  // Update manifest
  part.status = "worktree-created";
  manifest.updatedAt = now();
  writeManifest(safeBranch, manifest);

  console.log(`\nOK: Part ${order} worktree created at ${worktreePath}`);
}

function cmdVerify(partNumber) {
  if (!partNumber) {
    console.error("Usage: pr-split.mjs verify <part-number>");
    process.exit(1);
  }
  const order = parseInt(partNumber, 10);
  const safeBranch = safeBranchName(getCurrentBranch());
  const manifest = requireManifest(safeBranch);
  const part = getPart(manifest, order);
  const worktreePath = getPartDir(safeBranch, part);

  if (!existsSync(worktreePath)) {
    console.error(`ERROR: Worktree not found at ${worktreePath}`);
    process.exit(1);
  }

  console.log(`Verifying part ${order} in ${worktreePath}...`);

  // Install dependencies if needed
  const pkgPath = join(worktreePath, "package.json");
  const nodeModules = join(worktreePath, "node_modules");
  if (existsSync(pkgPath) && !existsSync(nodeModules)) {
    console.log("Installing dependencies...");
    if (existsSync(join(worktreePath, "bun.lockb"))) {
      run("bun install --frozen-lockfile", {
        cwd: worktreePath,
        allowFail: true,
        inheritStdio: true,
      });
    } else if (existsSync(join(worktreePath, "pnpm-lock.yaml"))) {
      run("pnpm install --frozen-lockfile", {
        cwd: worktreePath,
        allowFail: true,
        inheritStdio: true,
      });
    } else if (existsSync(join(worktreePath, "yarn.lock"))) {
      run("yarn install --frozen-lockfile", {
        cwd: worktreePath,
        allowFail: true,
        inheritStdio: true,
      });
    } else {
      run("npm ci", {
        cwd: worktreePath,
        allowFail: true,
        inheritStdio: true,
      });
    }
  }

  // Detect typecheck command
  let typecheckCmd = "";
  if (existsSync(pkgPath)) {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
    const scripts = pkg.scripts || {};
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };

    if (existsSync(join(worktreePath, "turbo.json")) && scripts.typecheck) {
      typecheckCmd = "npm run typecheck";
    } else if (scripts.typecheck) {
      typecheckCmd = "npm run typecheck";
    } else if (scripts["type-check"]) {
      typecheckCmd = "npm run type-check";
    } else if (deps.typescript) {
      typecheckCmd = "npx tsc --noEmit";
    }
  }

  if (!typecheckCmd) {
    console.log("WARN: No typecheck command detected. Marking as verified.");
    part.status = "verified";
    manifest.updatedAt = now();
    writeManifest(safeBranch, manifest);
    return;
  }

  console.log(`Running: ${typecheckCmd}`);
  try {
    run(typecheckCmd, { cwd: worktreePath, inheritStdio: true });
    console.log(`\nOK: Typecheck passed for part ${order}`);
    part.status = "verified";
    manifest.updatedAt = now();
    writeManifest(safeBranch, manifest);
  } catch {
    console.error(`\nFAIL: Typecheck failed for part ${order}`);
    process.exit(1);
  }
}

function cmdCreatePr(partNumber) {
  if (!partNumber) {
    console.error("Usage: pr-split.mjs create-pr <part-number>");
    process.exit(1);
  }

  try {
    run("which gh");
  } catch {
    console.error("ERROR: gh CLI not found. Install it to create PRs.");
    process.exit(1);
  }

  const order = parseInt(partNumber, 10);
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = requireManifest(safeBranch);
  const part = getPart(manifest, order);
  const worktreePath = getPartDir(safeBranch, part);

  // Validate before pushing
  const vResult = runValidation({ skipWorktreeCheck: true });
  if (!vResult.pass) {
    printValidation(vResult);
    console.error("\nAborted: fix validation issues before creating PRs.");
    process.exit(1);
  }

  // Push
  console.log(`Pushing ${part.branch}...`);
  git(`push -u origin "${part.branch}"`, { cwd: worktreePath });

  const body = buildPrBody(manifest, part);
  const bodyFile = join(worktreePath, ".pr-split-body");
  writeFileSync(bodyFile, body);

  const prUrl = run(
    `gh pr create --base "${manifest.baseBranch}" --title "${part.title}" --body-file "${bodyFile}"`,
    { cwd: worktreePath },
  );
  rmSync(bodyFile, { force: true });

  console.log(`PR created: ${prUrl}`);

  const prNumberMatch = prUrl.match(/\/(\d+)$/);
  const prNumber = prNumberMatch ? parseInt(prNumberMatch[1], 10) : null;

  part.status = "pr-created";
  part.prNumber = prNumber;
  part.prUrl = prUrl;
  manifest.updatedAt = now();
  writeManifest(safeBranch, manifest);

  console.log(prUrl);
}

function cmdUpdatePr(partNumber) {
  if (!partNumber) {
    console.error("Usage: pr-split.mjs update-pr <part-number>");
    process.exit(1);
  }

  try {
    run("which gh");
  } catch {
    console.error("ERROR: gh CLI not found. Install it to update PRs.");
    process.exit(1);
  }

  const order = parseInt(partNumber, 10);
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = requireManifest(safeBranch);
  const part = getPart(manifest, order);

  if (!part.prNumber) {
    console.error(
      `ERROR: Part ${order} has no PR number. Run create-pr first.`,
    );
    process.exit(1);
  }

  console.log(`Updating PR #${part.prNumber} title to: ${part.title}`);
  run(`gh pr edit ${part.prNumber} --title "${part.title}"`);

  const body = buildPrBody(manifest, part);
  const branchDir = getBranchDir(safeBranch);
  mkdirSync(branchDir, { recursive: true });
  const bodyFile = join(branchDir, ".pr-split-body");
  writeFileSync(bodyFile, body);

  run(`gh pr edit ${part.prNumber} --body-file "${bodyFile}"`);
  rmSync(bodyFile, { force: true });

  console.log(`OK: PR #${part.prNumber} updated.`);
}

function cmdUpdateAllPrs() {
  try {
    run("which gh");
  } catch {
    console.error("ERROR: gh CLI not found. Install it to update PRs.");
    process.exit(1);
  }

  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = requireManifest(safeBranch);

  const activeParts = manifest.parts.filter(
    (p) => p.status !== "merged" && p.prNumber,
  );

  if (activeParts.length === 0) {
    console.log("No open PRs to update.");
    return;
  }

  console.log(`Updating ${activeParts.length} PR(s) with review order...\n`);

  const branchDir = getBranchDir(safeBranch);
  mkdirSync(branchDir, { recursive: true });
  const bodyFile = join(branchDir, ".pr-split-body");

  for (const part of activeParts) {
    console.log(`  #${part.prNumber} — ${part.title}`);
    run(`gh pr edit ${part.prNumber} --title "${part.title}"`);

    const body = buildPrBody(manifest, part);
    writeFileSync(bodyFile, body);
    run(`gh pr edit ${part.prNumber} --body-file "${bodyFile}"`);
  }

  rmSync(bodyFile, { force: true });
  console.log(`\nOK: All ${activeParts.length} PRs updated.`);
}

function cmdPushUpdate(partNumber) {
  if (!partNumber) {
    console.error("Usage: pr-split.mjs push-update <part-number>");
    process.exit(1);
  }

  const order = parseInt(partNumber, 10);
  const safeBranch = safeBranchName(getCurrentBranch());
  const manifest = requireManifest(safeBranch);
  const part = getPart(manifest, order);
  const worktreePath = getPartDir(safeBranch, part);

  if (!existsSync(worktreePath)) {
    console.error(
      `ERROR: Worktree not found at ${worktreePath}. Run execute first.`,
    );
    process.exit(1);
  }

  console.log(`Force-pushing ${part.branch}...`);
  git(`push --force-with-lease -u origin "${part.branch}"`, {
    cwd: worktreePath,
  });

  if (part.status === "worktree-created") {
    part.status = "pr-created";
  }
  manifest.updatedAt = now();
  writeManifest(safeBranch, manifest);

  console.log(`OK: Part ${order} pushed.`);
}

function cmdStatus() {
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = readManifest(safeBranch);
  const branchDir = getBranchDir(safeBranch);

  if (!manifest) {
    console.log("No PR split manifest found for this branch.");
    console.log("Run /pr-split to create one.");
    return;
  }

  console.log(
    `PR Split Status for ${currentBranch} [${manifest.featureTag}]`,
  );
  console.log("");

  const hdr = [
    "#".padEnd(3),
    "Title".padEnd(55),
    "Status".padEnd(15),
    "PR",
  ].join(" | ");
  console.log(hdr);
  console.log(
    ["---".padEnd(3), "-".repeat(55), "-".repeat(15), "------"].join("-|-"),
  );

  for (const part of manifest.parts) {
    const prCol = part.prNumber ? `#${part.prNumber}` : "-";
    const row = [
      String(part.order).padEnd(3),
      part.title.substring(0, 55).padEnd(55),
      part.status.padEnd(15),
      prCol,
    ].join(" | ");
    console.log(row);
  }

  console.log("");
  console.log(`Branch dir: ${branchDir}/`);
  console.log(`Manifest:   ${getManifestPath(safeBranch)}`);
}

function cmdCleanup() {
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = readManifest(safeBranch);

  if (!manifest) {
    console.log("No manifest found. Nothing to clean up.");
    return;
  }

  let cleaned = 0;

  for (const part of manifest.parts) {
    if (part.status === "merged") continue;
    if (!part.prNumber) continue;

    let prState;
    try {
      prState = run(
        `gh pr view ${part.prNumber} --json state --jq '.state'`,
      );
    } catch {
      prState = "UNKNOWN";
    }

    if (prState === "MERGED") {
      console.log(
        `Cleaning part ${part.order}: ${part.branch} (merged as #${part.prNumber})`,
      );

      const wtPath = getPartDir(safeBranch, part);
      git(`worktree remove "${wtPath}" --force`, { allowFail: true });
      git(`branch -d "${part.branch}"`, { allowFail: true });
      git(`branch -D "${part.branch}"`, { allowFail: true });

      part.status = "merged";
      cleaned++;
    }
  }

  console.log(`\nCleaned ${cleaned} merged part(s).`);

  // Check if all parts are merged
  const remaining = manifest.parts.filter((p) => p.status !== "merged");
  if (remaining.length === 0) {
    console.log(
      `All parts merged. Removing branch directory for ${currentBranch}.`,
    );
    const branchDir = getBranchDir(safeBranch);
    rmSync(branchDir, { recursive: true, force: true });

    // Remove worktree parent if empty
    const worktreeParent = getWorktreeParent();
    try {
      const entries = readdirSync(worktreeParent);
      if (entries.length === 0) rmdirSync(worktreeParent);
    } catch {}
    return;
  }

  manifest.updatedAt = now();
  writeManifest(safeBranch, manifest);
}

function cmdSync() {
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = requireManifest(safeBranch);

  const baseBranch = manifest.baseBranch;

  // Get current diff files with their actions (three-dot = since merge base)
  const nameStatus = git(`diff ${baseBranch}...HEAD --name-status`, {
    allowFail: true,
  })
    .split("\n")
    .filter(Boolean);

  // Also get two-dot diff (actual difference from base tip) to filter out
  // files that were changed on this branch but already merged via other PRs
  const twoDotFiles = new Set(
    git(`diff origin/${baseBranch} HEAD --name-only`, { allowFail: true })
      .split("\n")
      .filter(Boolean),
  );

  const currentFiles = [];
  const currentActions = {};
  for (const line of nameStatus) {
    const [action, file] = line.split("\t");
    if (file && twoDotFiles.has(file)) {
      currentFiles.push(file);
      currentActions[file] = action;
    }
  }
  currentFiles.sort();

  // Build set of files owned by ACTIVE (non-merged) parts
  const activeFiles = new Set();
  for (const part of manifest.parts) {
    if (part.status === "merged") continue;
    for (const file of part.files) {
      activeFiles.add(file);
    }
  }

  // Build set of ALL manifest files (including merged)
  const allManifestFiles = new Set(manifest.parts.flatMap((p) => p.files));

  const currentSet = new Set(currentFiles);

  console.log(`Sync Report for ${currentBranch} (base: ${baseBranch})\n`);

  // 1. Orphan files
  const orphanFiles = currentFiles.filter((f) => !activeFiles.has(f));

  console.log("=== Orphan files (not owned by any active PR) ===");
  if (orphanFiles.length > 0) {
    for (const f of orphanFiles) {
      const action = currentActions[f] || "?";
      const reason = allManifestFiles.has(f)
        ? "owned by merged part"
        : "new file";
      console.log(`  ${action}\t${f} (${reason})`);
    }
  } else {
    console.log("(none)");
  }

  // 2. Removed files
  const removedFiles = [];
  for (const part of manifest.parts) {
    if (part.status === "merged") continue;
    for (const file of part.files) {
      if (!currentSet.has(file)) {
        removedFiles.push({ file, part: part.order });
      }
    }
  }

  console.log("\n=== Removed files (in active parts, no longer in diff) ===");
  if (removedFiles.length > 0) {
    for (const { file, part } of removedFiles) {
      console.log(`  ${file} (part ${part})`);
    }
  } else {
    console.log("(none)");
  }

  // 3. Detect stale parts
  const staleParts = [];

  for (const part of manifest.parts) {
    if (part.status === "merged") continue;

    const worktreePath = getPartDir(safeBranch, part);
    if (!existsSync(worktreePath)) {
      staleParts.push({ part, reason: "no worktree" });
      continue;
    }

    for (const file of part.files) {
      const action = part.fileActions?.[file] || "M";
      if (action === "D") continue;

      const sourceHash = git(`rev-parse "${currentBranch}:${file}"`, {
        allowFail: true,
      });
      const worktreeHash = git(`rev-parse HEAD:${file}`, {
        cwd: worktreePath,
        allowFail: true,
      });

      if (sourceHash && worktreeHash && sourceHash !== worktreeHash) {
        staleParts.push({ part, reason: `stale file: ${file}` });
        break;
      }
    }
  }

  console.log("\n=== Stale parts (worktree out of date) ===");
  if (staleParts.length > 0) {
    for (const { part, reason } of staleParts) {
      console.log(`  Part ${part.order}: ${part.title} (${reason})`);
    }
  } else {
    console.log("(none)");
  }

  // Structured JSON summary
  const summary = {
    orphanFiles: orphanFiles.map((f) => ({
      file: f,
      action: currentActions[f] || "?",
      reason: allManifestFiles.has(f) ? "merged-part" : "new",
    })),
    removedFiles,
    staleParts: staleParts.map((s) => ({
      order: s.part.order,
      reason: s.reason,
    })),
  };

  console.log("\n=== SYNC_JSON ===");
  console.log(JSON.stringify(summary));

  // Run validation as final gate
  const vResult = runValidation({ skipWorktreeCheck: true });
  printValidation(vResult);
  if (!vResult.pass) {
    process.exit(1);
  }
}

function runValidation({ skipWorktreeCheck = false } = {}) {
  const currentBranch = getCurrentBranch();
  const safeBranch = safeBranchName(currentBranch);
  const manifest = readManifest(safeBranch);

  if (!manifest) {
    return { pass: false, errors: ["No manifest found for this branch."], summary: "" };
  }

  const baseBranch = manifest.baseBranch;
  const errors = [];

  // 1. Get all files in the diff (two-dot = actual difference from base tip)
  const diffFiles = new Set(
    git(`diff origin/${baseBranch} HEAD --name-only`, { allowFail: true })
      .split("\n")
      .filter(Boolean),
  );

  // 2. Build file → part mapping from active parts
  const fileToPart = new Map();
  const activeParts = manifest.parts.filter((p) => p.status !== "merged");
  for (const part of activeParts) {
    for (const file of part.files) {
      if (fileToPart.has(file)) {
        errors.push(
          `DUPLICATE: ${file} is in Part ${fileToPart.get(file)} AND Part ${part.order}`,
        );
      }
      fileToPart.set(file, part.order);
    }
  }
  const manifestFiles = new Set(fileToPart.keys());

  // 3. Orphan files: in diff but not owned by any active part
  const orphans = [...diffFiles].filter((f) => !manifestFiles.has(f)).sort();
  for (const f of orphans) {
    errors.push(`ORPHAN: ${f} is in the diff but not assigned to any PR`);
  }

  // 4. Stale files: in active parts but no longer in diff
  const stale = [...manifestFiles].filter((f) => !diffFiles.has(f)).sort();
  for (const f of stale) {
    errors.push(
      `STALE: ${f} is in Part ${fileToPart.get(f)} but no longer in the diff`,
    );
  }

  // 5. Check worktree file hashes match source branch
  if (!skipWorktreeCheck) {
    for (const part of activeParts) {
      const worktreePath = getPartDir(safeBranch, part);
      if (!existsSync(worktreePath)) {
        errors.push(
          `MISSING_WORKTREE: Part ${part.order} (${part.slug}) has no worktree`,
        );
        continue;
      }

      for (const file of part.files) {
        const action = part.fileActions?.[file] || "M";
        if (action === "D") continue;

        const sourceHash = git(`rev-parse "${currentBranch}:${file}"`, {
          allowFail: true,
        });
        const worktreeHash = git(`rev-parse HEAD:${file}`, {
          cwd: worktreePath,
          allowFail: true,
        });

        if (sourceHash && worktreeHash && sourceHash !== worktreeHash) {
          errors.push(
            `OUT_OF_SYNC: Part ${part.order} file ${file} differs from source branch`,
          );
        }
      }
    }
  }

  // 6. Check numbering consistency
  const orders = activeParts.map((p) => p.order).sort((a, b) => a - b);
  const expectedTotal = activeParts.length;
  for (let i = 0; i < orders.length; i++) {
    if (orders[i] !== i + 1) {
      errors.push(
        `NUMBERING: Expected part ${i + 1} but found part ${orders[i]}`,
      );
    }
  }
  for (const part of activeParts) {
    if (part.total !== expectedTotal) {
      errors.push(
        `TOTAL_MISMATCH: Part ${part.order} has total=${part.total} but expected ${expectedTotal}`,
      );
    }
  }

  const summary = `${currentBranch} → ${baseBranch} | ${diffFiles.size} diff files, ${manifestFiles.size} manifest files, ${activeParts.length} active parts`;
  return { pass: errors.length === 0, errors, summary };
}

function printValidation(result) {
  console.log(`\nValidate: ${result.summary}\n`);
  if (result.pass) {
    console.log("PASS: All files accounted for. No issues found.");
  } else {
    console.log(`FAIL: ${result.errors.length} issue(s) found:\n`);
    for (const err of result.errors) {
      console.log(`  ✗ ${err}`);
    }
  }
}

function cmdValidate() {
  const result = runValidation();
  printValidation(result);
  process.exit(result.pass ? 0 : 1);
}

// ─── Main ────────────────────────────────────────────────────────────────────

const [cmd, ...args] = process.argv.slice(2);

const commands = {
  preflight: () => cmdPreflight(),
  context: () => cmdContext(args[0]),
  diff: () => cmdDiff(args[0]),
  manifest: () => cmdManifestRead(),
  "plan-save": () => cmdPlanSave(),
  execute: () => cmdExecute(args[0]),
  verify: () => cmdVerify(args[0]),
  "create-pr": () => cmdCreatePr(args[0]),
  "update-pr": () => cmdUpdatePr(args[0]),
  "update-all-prs": () => cmdUpdateAllPrs(),
  "push-update": () => cmdPushUpdate(args[0]),
  status: () => cmdStatus(),
  cleanup: () => cmdCleanup(),
  sync: () => cmdSync(),
  validate: () => cmdValidate(),
};

if (cmd === "help" || !cmd || !commands[cmd]) {
  console.log(`Usage: pr-split.mjs <command> [args]

Commands:
  preflight        Check required dependencies (git, gh)
  context [base]   Print repository context as JSON
  diff [base]      Print diff info against base branch (default: main)
  manifest         Read current manifest JSON
  plan-save        Save split plan to manifest (reads JSON from stdin)
  execute <N>      Create worktree and apply files for part N
  verify <N>       Run typecheck in part N's worktree
  create-pr <N>    Push branch and create GitHub PR for part N
  update-pr <N>    Update GitHub PR title and body for part N
  push-update <N>  Force-push rebased branch for part N
  status           Show status table for current branch
  cleanup          Remove worktrees/branches for merged PRs
  update-all-prs   Update title + body (with review order) for all open PRs
  validate         Check all diff files are covered, no orphans/stale/duplicates
  sync             Detect orphan files, stale worktrees; output SYNC_JSON`);
  process.exit(cmd === "help" || !cmd ? 0 : 1);
}

commands[cmd]();
