/** Trusted Effect slop review policy for Luna's standards specialists. */
export const effectSlopcopReview = `## effect-slopcop

Apply this review policy only to Effect projects: establish applicability from the changed package's dependencies and source imports in the immutable snapshot. In mixed repositories, scope it to the Effect-owned code and its boundaries, not unrelated packages. Inspect the pinned Effect version and source before recommending APIs; use version-appropriate equivalents rather than prescribing unavailable APIs or an unsolicited migration.

Check every applicable rule below across the complete change. The standards-contracts specialist owns rules 1–5, 9–12, and 14–17; the standards-modules specialist owns rules 6–8, 13, and 18–19. Trace surrounding callers and boundaries to verify each candidate, but report only issues introduced or materially exposed by this change. These are explicit standards, not generic style preferences. Emit findings as category standards with a rule citation of effect-slopcop/<number>, a concrete location, the modeling or maintenance impact, and an actionable correction. Keep findings local to Luna; send wider behavioral or architectural consequences as seam notes for Astra.

1. Option instead of NullOr: model internal absence with Option. Keep NullOr, null, and undefined only at an actual I/O boundary, translating to the internal model as data enters.
2. Tagged-union matching: model variants with Schema-backed tagged unions and prefer the union's match API over importing Effect Match for tag dispatch. Reserve direct Match.value for schema-modeled literal alternatives (Schema.Literals or the pinned-version equivalent); inspect Match.when as a sign that the domain alternatives have not been modeled. Do not create a wrapper solely to hide a Match import.
3. Exhaustive branches: replace chains of if statements dispatching on domain alternatives with matching plus exhaustiveness. A single guard or independent checks are not a multi-variant dispatch.
4. Exhaustive expressions: replace multiple or nested ternaries dispatching on alternatives with exhaustive matching over the modeled alternatives.
5. No direct tag access: use the model's matcher or supported predicates rather than reading .tag or ._tag to dispatch, compare, or narrow variants.
6. Happy path first: keep successful work free of recovery branches. Finish the happy-path .pipe first, then attach a separate final .pipe for catchTag or other typed error recovery. Preserve error distinctions, defects, interruption, and resource cleanup.
7. Effect failures: model failures in Effect's error channel with Schema-backed errors rather than manually throwing. Capture throwing third-party I/O in the owning boundary and translate its failures there.
8. Immutable collections: use Effect HashMap and HashSet rather than JavaScript Map and Set for internal collections. When mutation is genuinely necessary, hold and update the immutable collection through Ref. Translate collection representations only where an external API requires them.
9. Schema before ternaries: inspect nested ternaries and ternaries producing {} for missing state or optional-field modeling. Correct the schema and match its alternatives rather than patching object shapes with conditional placeholders.
10. Schema codecs at boundaries: use schema decode/encode and schema transformations for external representations instead of hand-written boundary encoding helpers. Keep protocol translation owned by the boundary.
11. Meaningful emptiness: represent semantic absence with Option rather than empty strings, empty objects, or other sentinel values. Preserve genuinely valid empty collections or text as values; convert absence to wire-level emptiness only during I/O encoding.
12. Audit undefined: trace each introduced undefined, optional property, and fallback to its origin. Fix the schema or Effect pattern so boundary optionality does not leak into internal behavior.
13. Remove single-use helpers: inline helpers used only once rather than adding indirection. Verify references before removal; preserve required framework callbacks, public contracts, and meaningful ownership or lifecycle boundaries, with concrete evidence for any exception.
14. No instanceof: use schema decoding, schema predicates, or modeled error/variant matching instead of instanceof checks. Translate foreign error identities at the adapter boundary.
15. Schema-owned tags: construct variants and errors through Schema-backed constructors, not manual _tag fields or hand-built tagged objects. A tag declared by the schema is the model definition, not a violation.
16. Schema inference over casts: treat as const, especially outside I/O, and type assertions as evidence of incomplete modeling. Prefer schema-derived inference and validated boundary values; establish why an assertion is necessary before accepting it.
17. Schema-first models: prefer Schema and derived types over independently maintained type or interface data models. Distinguish data/state/error models from behavior-only service contracts and required library interfaces.
18. Port/adapter boundaries: trace changed inputs, outputs, errors, and dependencies across ports and adapters. Keep provider DTOs, nullable wire formats, platform APIs, and encoding details inside adapters; expose domain/application models through ports and preserve dependency direction.
19. Construction and composition ownership: verify make* returns a service-construction Effect; *Layer owns meaningful reusable composition or lifecycle rather than a trivial registration alias. Perform service registration and provider composition once at the composition root, never at operation call sites. Trace construction, provisioning, scope, and reuse to detect repeated registrations or lifetimes hidden in callers.

Complete only after every assigned rule has been checked for every relevant changed model, branch, helper, collection, error flow, boundary, and service. A search hit is a candidate, not proof: verify actual ownership and semantics before reporting. Reviewers remain read-only; recommend fixes without editing the snapshot or source repository.`
